const constants = {
  NEXT_PUBLIC_CHAIN_ID: process.env.NEXT_PUBLIC_CHAIN_ID ?? "56",
  NEXT_PUBLIC_CHAIN_NAME:
    process.env.NEXT_PUBLIC_CHAIN_NAME ?? "BNB Chain",
  NEXT_PUBLIC_ZARAI_TOKEN_ADDRESS:
    process.env.NEXT_PUBLIC_ZARAI_TOKEN_ADDRESS ??
    "0xb6F69E830E13f6Dd57edBCC7B12d18299E131323",
  NEXT_PUBLIC_SALE_CONTRACT_ADDRESS:
    process.env.NEXT_PUBLIC_SALE_CONTRACT_ADDRESS ??
    "0xb509dF201C4dA14cCc1Ce925ba7ad7Db33Ae6AcF",
  NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS:
    process.env.NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS ??
    "0x55d398326f99059fF775485246999027B3197955",
  NEXT_PUBLIC_TREASURY_WALLET:
    process.env.NEXT_PUBLIC_TREASURY_WALLET ??
    "0x40a44BCd809d8cfB9449BF7d2f7D249517ddFe09",
  NEXT_PUBLIC_INITIAL_SALE_ALLOCATION:
    process.env.NEXT_PUBLIC_INITIAL_SALE_ALLOCATION ?? "560000",
  NEXT_PUBLIC_BSCSCAN_BASE_URL:
    process.env.NEXT_PUBLIC_BSCSCAN_BASE_URL ?? "https://bscscan.com",
  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID:
    process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID ?? "",
  NEXT_PUBLIC_BSCSCAN_API_KEY:
    process.env.NEXT_PUBLIC_BSCSCAN_API_KEY ?? "",
} as const;

export { constants };
